### ISSUE TITLE
Need help to train the RGN model

### ISSUE THREAD

**Issue by iamxpy** [uta-smile/RetroXpert#6]
I tried to train the RGN model with the command `bash train.sh`, but the console only outputed one line of message, so it seemed like I haven't started the training successfully.

```
(nips) xiepengyu@c03:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$ bash train.sh
[2021-01-08 10:46:24,090 INFO] Loading dataset from ../../data/USPTO50K-aug-typed/USPTO50K-aug-typed.train.0.pt
```

The only change I made is adding `export CUDA_VISIBLE_DEVICES=1,2` to `train.sh`:

```
dataset=USPTO50K-aug-typed

export CUDA_VISIBLE_DEVICES=1,2

python  ../../onmt/bin/train.py --data ../../data/${dataset}/${dataset} \
    --save_model ../../experiments/checkpoints/${dataset}/${dataset}_model \
    --seed 42 --world_size 2 --gpu_ranks 0 1 --save_checkpoint_steps 10000 --keep_checkpoint 10 \
    --train_steps 300000 --param_init 0  --param_init_glorot --max_generator_batches 32 \
    --batch_size 4096 --batch_type tokens --normalization tokens --max_grad_norm 0  --accum_count 4 \
    --optim adam --adam_beta1 0.9 --adam_beta2 0.998 --decay_method noam --warmup_steps 8000  \
    --learning_rate 2 --label_smoothing 0.0 --report_every 1000 --valid_steps 10000 \
    --layers 4 --rnn_size 256 --word_vec_size 256 --encoder_type transformer --decoder_type transformer \
    --dropout 0.1 --position_encoding --share_embeddings \
    --global_attention general --global_attention_function softmax --self_attn_type scaled-dot \
    --heads 8 --transformer_ff 2048 --master_port 10001
```

What am I doing wrong?

**Comment by chaoyan1037** [comment]
I am not sure, have you followed all procedures?

**Comment by iamxpy** [comment]
> I am not sure, have you followed all procedures?

Yes, and here are some of the results:

```
(nips) xiepengyu@c03:~/RetroXpert$ python preprocessing.py
preprocessing dataset USPTO50K...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5007/5007 [00:25<00:00, 199.92it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5001/5001 [00:29<00:00, 170.43it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40008/40008 [03:03<00:00, 217.77it/s]
5007it [00:15, 322.15it/s]
size 5007
5001it [00:15, 315.40it/s]
size 5001
40008it [02:03, 323.56it/s]
size 40008
(nips) xiepengyu@c03:~/RetroXpert$ python extract_semi_template_pattern.py --extract_pattern
extract semi templates for dataset USPTO50K...
total training rxns: 40008
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40008/40008 [05:00<00:00, 133.19it/s]
(nips) xiepengyu@c03:~/RetroXpert$ python extract_semi_template_pattern.py
extract semi templates for dataset USPTO50K...
load semi template patterns from file: ./data/USPTO50K/product_patterns.txt
total number of semi template patterns: 647
 12%|███████████████████▋                                                                                                                                           | 4954/40008 [00:41<04:37, 126.41it/s]
[IH:19]
 38%|████████████████████████████████████████████████████████████▊                                                                                                 | 15398/40008 [02:05<02:49, 145.53it/s]
[BrH:4]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40008/40008 [05:00<00:00, 133.13it/s]
# ave center per mol: 36.74635072985403
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5001/5001 [00:37<00:00, 132.33it/s]
# ave center per mol: 36.901419716056786
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 3372/5007 [00:24<00:12, 133.22it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5007/5007 [00:37<00:00, 131.82it/s]
# ave center per mol: 36.70041941282205

(nips) xiepengyu@c03:~/RetroXpert$ CUDA_VISIBLE_DEVICES=2 python train.py --typed
Namespace(batch_size=32, dataset='USPTO50K', epochs=80, exp_name='USPTO50K_typed', gat_layers=3, heads=4, hidden_dim=128, in_dim=704, load=False, logdir='logs', lr=0.0005, seed=123, test_on_train=False,
 test_only=False, typed=True, use_cpu=False, valid_only=False)
Counter({1: 3482, 0: 1415, 2: 102, 9: 1, 17: 1})
Counter({1: 27851, 0: 11296, 2: 849, 3: 4, 4: 4, 10: 2, 7: 1, 13: 1})
Epoch 1: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 1251/1251 [03:39<00:00,  5.70it/s, acc=0.41767, loss=4.08270, loss_ce=3.86544, loss_h=0.21726]
Train Loss: 4.08270
.......
Epoch 80: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1251/1251 [03:20<00:00,  6.25it/s, acc=0.91017, loss=0.44533, loss_ce=0.43633, loss_h=0.00900]
Train Loss: 0.44533
Train Bond Disconnection Acc: 0.91017
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [01:12<00:00,  1.81s/it]
Bond disconnection number prediction acc: 0.991602
Loss:  4.041077407687408
Bond disconnection acc (without auxiliary task): 0.818836

(nips) xiepengyu@c03:~/RetroXpert$ CUDA_VISIBLE_DEVICES=1 python train.py --typed --test_only  --load
Namespace(batch_size=32, dataset='USPTO50K', epochs=80, exp_name='USPTO50K_typed', gat_layers=3, heads=4, hidden_dim=128, in_dim=704, load=True, logdir='logs', lr=0.0005, seed=123, test_on_train=False,
test_only=True, typed=True, use_cpu=False, valid_only=False)
Counter({1: 3486, 0: 1411, 2: 109, 11: 1})
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:59<00:00,  1.48s/it]
pred_true_list size: 5007
Bond disconnection number prediction acc: 0.992211
Loss:  4.209371869616911
Bond disconnection acc (without auxiliary task): 0.812463

(nips) xiepengyu@c03:~/RetroXpert$ python prepare_data.py --typed
Namespace(dataset='USPTO50K', output_suffix='-aug-typed', typed=True)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5001/5001 [00:03<00:00, 1664.89it/s]
src_file: OpenNMT-py/data/USPTO50K-aug-typed/src-valid.txt
tgt_file: OpenNMT-py/data/USPTO50K-aug-typed/tgt-valid.txt
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68372/68372 [00:41<00:00, 1634.73it/s]
src_file: OpenNMT-py/data/USPTO50K-aug-typed/src-train-aug.txt
tgt_file: OpenNMT-py/data/USPTO50K-aug-typed/tgt-train-aug.txt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5007/5007 [00:03<00:00, 1661.67it/s]
src_file: OpenNMT-py/data/USPTO50K-aug-typed/src-test.txt
tgt_file: OpenNMT-py/data/USPTO50K-aug-typed/tgt-test.txt

(nips) xiepengyu@c03:~/RetroXpert$ python prepare_test_prediction.py  --typed
Namespace(dataset='USPTO50K', output_suffix='-aug-typed', typed='typed')
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5007/5007 [00:01<00:00, 4386.84it/s]
guided bond_disconnection prediction cnt and acc: 4336 0.8659876173357299
bond_disconnection len: 5007
save src_test_prediction: OpenNMT-py/data/USPTO50K-aug-typed/src-test-prediction.txt
double check guided synthon prediction acc: 0.8663870581186339

(nips) xiepengyu@c03:~/RetroXpert$ python prepare_train_error_aug.py  --typed
Namespace(dataset='USPTO50K', output_suffix='-aug-typed', typed='typed')
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40008/40008 [00:29<00:00, 1369.39it/s]
guided bond_disconnection prediction cnt and acc: 38219 0.9552839432113577
bond_disconnection len: 40008
augmentation data size: 1789
save src_train_aug_err: OpenNMT-py/data/USPTO50K-aug-typed/src-train-aug-err.txt
save tgt_train_aug_err: OpenNMT-py/data/USPTO50K-aug-typed/tgt-train-aug-err.txt

```

**Comment by chaoyan1037** [comment]
Have you generated data by *bash preprocess.sh*?

**Comment by iamxpy** [comment]
> Have you generated data by _bash preprocess.sh_?

Yes, I have run the command, but forget to paste the result above, sorry for that.

```
(nips) xiepengyu@c03:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$ bash preprocess.sh
[2021-01-08 10:17:13,386 INFO] Extracting features...
[2021-01-08 10:17:13,386 INFO]  * number of source features: 0.
[2021-01-08 10:17:13,386 INFO]  * number of target features: 0.
[2021-01-08 10:17:13,386 INFO] Building `Fields` object...
[2021-01-08 10:17:13,386 INFO] Building & saving training data...
[2021-01-08 10:17:13,550 INFO] Building shard 0.
[2021-01-08 10:17:16,002 INFO]  * saving 0th train data shard to /home/xiepengyu/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed/../../data/USPTO50K-aug-typed/USPTO50K-aug-typed.train.0.pt.
[2021-01-08 10:17:20,922 INFO]  * tgt vocab size: 69.
[2021-01-08 10:17:20,922 INFO]  * src vocab size: 79.
[2021-01-08 10:17:20,922 INFO]  * merging src and tgt vocab...
[2021-01-08 10:17:20,922 INFO]  * merged vocab size: 91.
[2021-01-08 10:17:20,923 INFO] Building & saving validation data...
[2021-01-08 10:17:20,940 INFO] Building shard 0.
[2021-01-08 10:17:21,033 INFO]  * saving 0th valid data shard to /home/xiepengyu/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed/../../data/USPTO50K-aug-typed/USPTO50K-aug-typed.valid.0.pt.

```

**Comment by chaoyan1037** [comment]
It still does not work? That is weird.

**Comment by iamxpy** [comment]
It turns out that I haven't set the `world_size` and `gpu_ranks` correctly before, now I set `world_size` to `4` and `gpu_ranks` to `2 3` because the server has 4 gpus and I would like to train the model on gpu 3 and 4. I also change the `batch_size` to `4` for testing. The whole `train.sh` file is as follows:

```sh
dataset=USPTO50K-aug-typed


python  ../../onmt/bin/train.py --data ../../data/${dataset}/${dataset} \
    --save_model ../../experiments/checkpoints/${dataset}/${dataset}_model \
    --seed 42 --world_size 4 --gpu_ranks 2 3 --save_checkpoint_steps 10000 --keep_checkpoint 10 \
    --train_steps 300000 --param_init 0  --param_init_glorot --max_generator_batches 32 \
    --batch_size 4 --batch_type tokens --normalization tokens --max_grad_norm 0  --accum_count 4 \
    --optim adam --adam_beta1 0.9 --adam_beta2 0.998 --decay_method noam --warmup_steps 8000  \
    --learning_rate 2 --label_smoothing 0.0 --report_every 1000 --valid_steps 10000 \
    --layers 4 --rnn_size 256 --word_vec_size 256 --encoder_type transformer --decoder_type transformer \
    --dropout 0.1 --position_encoding --share_embeddings \
    --global_attention general --global_attention_function softmax --self_attn_type scaled-dot \
    --heads 8 --transformer_ff 2048 --master_port 10001

```

But when I run `bash train.sh` with above configuration, I get the following error:

```python
(nips) xiepengyu@c03:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$ bash train.sh
training ......
[2021-01-16 20:54:39,614 INFO] Loading dataset from ../../data/USPTO50K-aug-typed/USPTO50K-aug-typed.train.0.pt
[2021-01-16 20:54:40,533 INFO] number of examples: 70161
[2021-01-16 20:54:40,618 WARNING] An example was ignored, more tokens than allowed by tokens batch_size
Traceback (most recent call last):
  File "../../onmt/bin/train.py", line 211, in <module>
    main()
  File "../../onmt/bin/train.py", line 207, in main
    train(opt)
  File "../../onmt/bin/train.py", line 86, in train
    p.join()
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "../../onmt/bin/train.py", line 190, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/xiepengyu/RetroXpert/OpenNMT-py/onmt/bin/train.py", line 144, in run
    gpu_rank = onmt.utils.distributed.multi_init(opt, device_id)
  File "/home/xiepengyu/RetroXpert/OpenNMT-py/onmt/utils/distributed.py", line 27, in multi_init
    world_size=dist_world_size, rank=opt.gpu_ranks[device_id])
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: connect() timed out.
```
Any suggestions would be highly appreciated, thx!

**Comment by chaoyan1037** [comment]
Could you please use the original scripts? If your machine is equipped with 4 GPUs, you may specify the GPUs when launching the script like:
```
CUDA_VISIBLE_DEVICES=2,3 bash train.sh
```

**Comment by iamxpy** [comment]
> Could you please use the original scripts? If your machine is equipped with 4 GPUs, you may specify the GPUs when launching the script like:
> 
> ```
> CUDA_VISIBLE_DEVICES=2,3 bash train.sh
> ```

When I use the original script the run the command `CUDA_VISIBLE_DEVICES=2,3 bash train.sh` on a machine equipped with 4 gpus, the program print two lines of message and exit:
```sh
(nips) xiepengyu@c03:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$ CUDA_VISIBLE_DEVICES=2,3 bash train.sh
[2021-01-17 10:53:28,000 INFO] Loading dataset from ../../data/USPTO50K-aug-typed/USPTO50K-aug-typed.train.0.pt
[2021-01-17 10:53:28,755 INFO] number of examples: 70161
(nips) xiepengyu@c03:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$
```

**Comment by iamxpy** [comment]
It seems like I have missed the `OpenNMT` package before, sorry for that.
